config/routes.rb
Rails.application.routes.draw do

  resources :wikis
  resources :collaborators, only: [:create, :destroy]

  devise_for :users

  get 'users/upgrade' #had to add this back in. refactoring below did not work.

  resources :users do
    collection do
      get "upgrade"
    end
    post "toggle_role"
    post "go_public"
  end

  resources :charges, only: [:new, :create]

  get 'welcome/index'

  root to: 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :collaborators
  has_many :collaborations, through: :collaborators, source: :wiki
  has_many :wikis

  after_initialize :set_role

  def admin?
    role == 'admin'
  end

  def premium?
    role == 'premium'
  end

  def public?
    role == 'public'
  end

  # sets default role on creation if null
  def set_role
    self.role ||= 'public'
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators
  belongs_to :user

  scope :default_order, -> () { order('wikis.created_at DESC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    flash[:error] = "You must sign in to make changes to the wiki."
    redirect_to root_url
    # alert: exception.message
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Membership - #{current_user.name}",
      amount: 10_00
    }
  end

#creates a new charge. Can i shove the user role update at the bottom of this?
  def create
    @amount = 10_00

    #creating Stripe customer object for unique charge
    customer = Stripe::Customer.create(
    email: current_user.email,
    card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: "Premium Membership - #{current_user.email}",
      currency: 'usd'
    )

    current_user.update_attributes!( role: 'premium' )

    flash[:success] = "Thank you for your payment, #{current_user.email}!"
    redirect_to welcome_index_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def create

    @wiki = Wiki.find(params[:wiki_id])
    @user = User.where(email: params[:email]).take

    # is there a class method for this check?
    if @user == nil
      flash[:error] = "Collaborator could not be found."
      redirect_to edit_wiki_path(@wiki)
    elsif @wiki.users.include?(@user)
      flash[:error] = "Collaborator already exists."
      redirect_to edit_wiki_path(@wiki)
    else
      collaborator = @wiki.collaborators.build(user_id: @user.id)

      if collaborator.save
        flash[:notice] = "Your collaborator has been added to the wiki."
        redirect_to edit_wiki_path(@wiki)
      else
        flash[:error] = "Collaborator could not be added. Check spelling!"
        redirect_to edit_wiki_path(@wiki)
      end
    end

  end


  def destroy

    @collaborator = Collaborator.find(params[:id])
    @wiki = @collaborator.wiki

    if @collaborator.destroy
      flash[:notice] = "Collaborator removed from wiki."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "Collaborator could not be removed."
      redirect_to edit_wiki_path(@wiki)
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def upgrade
    @user = current_user
  end

# switches role between public and premium
  def toggle_role
    @user = current_user

    if @user.admin? == 'admin'
      flash[:error] = "User is an admin. No update."
    elsif @user.public?
      @user.update_attribute(:role, 'premium')
      flash[:notice] = "User switched from public to premium."
    else
      @user.update_attribute(:role, 'public')
      flash[:notice] = "User switched from premium to public."
    end
    redirect_to users_upgrade_path
  end

  def go_premium
    @user = current_user
    @user.update_attribute(:role, 'premium')
  end

  def go_public
    @user = current_user
    @user.update_attribute(:role, 'public')
    flash[:notice] = "User switched from premium to public."
    redirect_to edit_user_registration_path
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = policy_scope(Wiki.paginate(page: params[:page], per_page: 10))
    authorize @wikis
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = current_user.wikis.build(params.require(:wiki).permit(:title, :body, :private))
    authorize @wiki
    # adding owner to collaborator list
    # collaborator = @wiki.collaborators.build(user_id: current_user.id)

    if @wiki.save
      flash[:notice] = "Wiki has been saved."
      redirect_to @wiki
    else
      flash[:notice] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.update_attributes(params.require(:wiki).permit(:title, :body, :private))
      flash[:notice] = "Wiki has been updated."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "There was an error updating the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    title = @wiki.title
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to @wiki
    else
      flash[:error] = "There was an error deleting the wiki."
      render :show
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = { fenced_code_blocks: true }
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
  
end

app/helpers/charges_controller_helper.rb
module ChargesControllerHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h1>ChargesController#create</h1>
<p>Find me in app/views/charges_controller/create.html.erb</p>

app/views/charges/new.html.erb
<div class="col-md-4">
  <h4>Upgrade to a private membership today!</h4>
  <ul>
    <li>Create Private wikis</li>
    <li>Add Collaborators to your private wikis</li>
    <li>One time cost of $10</li>
  </ul>
</div>

<div class="col-md-4">
  <%= form_tag charges_path do %>
    <script class='stripe-button'
      src="https://checkout.stripe.com/checkout.js"
      data-key="<%= @stripe_btn_data[:key] %>"
      data-amount=<%= @stripe_btn_data[:amount] %>
      data-description="<%= @stripe_btn_data[:description] %>" >
    </script>
  <% end %>
</div>

app/views/collaborators/_collaborators.html.erb
<!-- form for taking in new collaborators -->
<% if @wiki.user == current_user %>
  <%= form_tag collaborators_path, method: :post do %>
    <%= text_field_tag :email %>
    <%= hidden_field_tag :wiki_id, @wiki.id %>
    <%= submit_tag "Add Collaborator" %>
  <% end %>
<% end %>

</br>

<!-- displays list of collaborators -->
<div class="container">
  <div class="row">
    <h4>Wiki Collaborators</h4>
    <% @wiki.collaborators.each do |collaborator| %>
      <p>
        <%= collaborator.user.email %>
        <!-- delete collaborator option only available to creator -->
        <% if @wiki.user == current_user %>
          <%= link_to "", [collaborator], method: :delete, class: 'glyphicon glyphicon-ok' %>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Welcome", welcome_index_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>

      <div class="pull-right user-info">
        <% if current_user %>
          Hello <%= link_to current_user.email, edit_user_registration_path %>! <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

  <%= yield %>

  </div>

</body>
</html>

app/views/users/upgrade.html.erb
<h1>Upgrade your account today!</h1>


<p>Current Role: <%= current_user.role %> </p>

<p>Click here to toggle your role. <%= button_to "Toggle", user_toggle_role_path(current_user), method: :post, class: 'btn btn-success' %></p>

<!-- also try form_for for practice -->

app/views/welcome/index.html.erb
<br/>
<div class="jumbotron">
  <h1>Blocipedia</h1>

  <% if current_user %>
    <p>
        <%= link_to "Wikis", wikis_path, class: 'btn btn-primary' %>
        <!-- distinguish between public and private
        replace private option with upgrade link if user not premium -->
  <% else %>
    <p>
        <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
    </p>
  <% end %>

</div>

<div class="row">
  <div class="col-md-6">
    <h2>Create Public Wikis for free.</h2>
    <p>View Public Wikis and Edit them as a free Public member! </br> Just <%= link_to "Sign Up", new_user_registration_path, class: 'link' %>!</p>
  </div>

  <div class="col-md-6">
    <h2>Create Private Wikis for you organization.</h2>
    <p>Collaborate with custom groups. </br>Manage prviate wikis. </br> Be eligible to join other Premium Wikis. </p>
    <p><%= link_to "Upgrade Today", new_charge_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/wikis/edit.html.erb
<%= link_to "Back to Wiki", @wiki %>
<h1>Edit Wiki</h1>
<br>
<br>
<div class="row">
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'from-control', placeholder: "Wiki Title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Wiki Body" %>
      </div>
      <div class="form-group">
        <% if (current_user.admin? || current_user.premium?) %>
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private Wiki?
          <% end %>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

<!-- provides field to add collaborator and shows existing collaborators -->
<div class="form-group">
  <%= render partial: 'collaborators/collaborators', locals: { wiki: @wiki, user: current_user } %>
</div>

app/views/wikis/index.html.erb
<h1>Wikis</h1>

<% if policy(Wiki.new).create? %>
  <%= link_to "New Wiki", new_wiki_path(), class: 'btn btn-success' %>
<% end %>

<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <p><%= link_to (markdown_to_html wiki.title), wiki %></p>
      </h4>
    </div>
  </div>
<% end %>

<%= will_paginate @wikis %>

app/views/wikis/new.html.erb
<h1>Create a New Wiki</h1>
<br>
<div class="row">
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'from-control', autofocus: true, placeholder: "Wiki Title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Wiki Body" %>
      </div>
      <div class="form-group">
        <!-- public of private checkbox -->
        <!-- modify view for user membership type -->
      <% if (current_user.admin? || current_user.premium?) %>
        <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Private Wiki?
        <% end %>
      <% end %>

      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<div class="container">

  <%= link_to "Back to wikis", wikis_path %>


  <% if policy(@wiki).show? %>
    <h1><%= markdown_to_html @wiki.title %></h1>
    <p><%= markdown_to_html @wiki.body %></p>
    <small>
      <i>authored by: <%= @wiki.user.name %></i>
      <p><%= render partial: 'collaborators/collaborators', locals: { wiki: @wiki, user: current_user } %></p>
    </small>
  <% end %>

    <br>

  <% if policy(@wiki).update? %>
    <%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete Wiki", [@wiki], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?' } %>
  <% end %>
</div>